name: Build Windows Executable
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.13'
          architecture: 'x64'
      - name: Install requirements and installer
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Run pyinstaller
        run: |
          python -m PyInstaller b2c.spec
      - run: ls dist
      - run: mv dist/b2c.exe .
      - run: ls .
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            ./b2c.exe